name: 'Setup VSTS Feed'
description: 'Setup a VSTS Feed and authenticate'
author: 'iamvishnusankar'
inputs:
  registry:
    deacription: 'VSTS private feed registry'
  always-auth:
    description: 'Set always-auth in npmrc'
    default: true
runs:
  using: 'node12'
  main: 'dist/bundle/index.js'
